import fs from 'node:fs';
import path from 'node:path';
import { root } from './toolchain.mjs';
const next = process.argv[2];
const file = path.join(root, 'package.json');
const metadata = JSON.parse(fs.readFileSync(file, 'utf8'));
if (!next || !/^\d+\.\d+\.\d+$/.test(next)) throw new Error('Usage: npm run android:version -- 1.2.1');
const oldParts = metadata.version.split('.').map(Number);
const newParts = next.split('.').map(Number);
const different = newParts.findIndex((part, index) => part !== oldParts[index]);
if (different < 0 || newParts[different] < oldParts[different]) throw new Error('The new version must increase.');
metadata.version = next;
metadata.androidVersionCode += 1;
if (metadata.androidVersionCode > 2_100_000_000) throw new Error('Android versionCode limit reached.');
const lockFile = path.join(root, 'package-lock.json');
const lock = JSON.parse(fs.readFileSync(lockFile, 'utf8'));
lock.version = next;
lock.packages[''].version = next;
fs.writeFileSync(file, JSON.stringify(metadata, null, 2) + '\n');
fs.writeFileSync(lockFile, JSON.stringify(lock, null, 2) + '\n');
console.log(`Version ${next}, Android build ${metadata.androidVersionCode}. Rebuild and upload an AAB using the same key.`);
