/* ── Mappings de types de contenu (sans dépendance React) ───────────────────
 * Ces maps sont volontairement « pures » : elles n'importent ni React ni
 * icônes, afin d'être consommables aussi bien par le front (badges, listes)
 * que par le pipeline d'import JSON (côté navigateur ET fonctions cloud).
 */

export const TYPE_MAP: { [key: string]: string } = {
  'definition': 'définition', 'définition': 'définition',
  'theorem': 'théorème', 'théorème': 'théorème', 'theoreme': 'théorème',
  'proposition': 'proposition', 'prop': 'proposition',
  'lemma': 'lemme', 'lemme': 'lemme',
  'corollary': 'corollaire', 'corollaire': 'corollaire', 'corol': 'corollaire',
  'remark': 'remarque', 'remarque': 'remarque', 'rem': 'remarque',
  'proof': 'preuve', 'preuve': 'preuve',
  'example': 'exemple', 'exemple': 'exemple', 'ex': 'exemple',
  'exercise': 'exercice', 'exercice': 'exercice', 'exo': 'exercice',
  'activity': 'activité', 'activité': 'activité', 'activite': 'activité', 'act': 'activité',
  'application': 'application', 'app': 'application',
  // SVT & Physique (communs)
  'observation': 'observation', 'obs': 'observation',
  'comparaison': 'comparaison', 'comparison': 'comparaison', 'comp': 'comparaison',
  'experience': 'expérience', 'expérience': 'expérience', 'exp': 'expérience',
  'interpretation': 'interprétation', 'interprétation': 'interprétation', 'interp': 'interprétation',
  'conclusion': 'conclusion', 'concl': 'conclusion',
  'methode': 'méthode', 'méthode': 'méthode', 'method': 'méthode',
  // SVT
  'introduction': 'introduction', 'intro': 'introduction',
  'classification': 'classification', 'classif': 'classification',
  'structure': 'structure', 'struct': 'structure',
  'fonction': 'fonction', 'function': 'fonction', 'fonc': 'fonction',
  'mecanisme': 'mécanisme', 'mécanisme': 'mécanisme', 'mechanism': 'mécanisme',
  'processus': 'processus', 'process': 'processus', 'proc': 'processus',
  // Physique
  'propriete': 'propriété', 'propriété': 'propriété', 'property': 'propriété', 'propr': 'propriété',
  'grandeur': 'grandeur', 'quantity': 'grandeur', 'grand': 'grandeur',
  'relation': 'relation', 'rel': 'relation',
  'loi': 'loi', 'law': 'loi',
  'principe': 'principe', 'principle': 'principe', 'princ': 'principe',
  'protocole': 'protocole', 'protocol': 'protocole', 'proto': 'protocole',
  'modele': 'modèle', 'modèle': 'modèle', 'model': 'modèle', 'mod': 'modèle',
  'securite': 'sécurité', 'sécurité': 'sécurité', 'safety': 'sécurité', 'sec': 'sécurité'
};

export const BADGE_TEXT_MAP: { [key: string]: string } = {
  'définition': 'Déf.',
  'théorème': 'Th.',
  'proposition': 'Prop.',
  'lemme': 'Lem.',
  'corollaire': 'Cor.',
  'remarque': 'Rem.',
  'preuve': 'Prv.',
  'exemple': 'Ex.',
  'exercice': 'Exo.',
  'activité': 'Act.',
  'application': 'Appli.',
  'introduction': 'Intro.',
  'observation': 'Obs.',
  'comparaison': 'Comp.',
  'classification': 'Classif.',
  'structure': 'Struct.',
  'fonction': 'Fonc.',
  'mécanisme': 'Méc.',
  'processus': 'Proc.',
  'méthode': 'Méth.',
  'expérience': 'Exp.',
  'interprétation': 'Interp.',
  'conclusion': 'Concl.',
  'propriété': 'Propr.',
  'grandeur': 'Grand.',
  'relation': 'Rel.',
  'loi': 'Loi',
  'principe': 'Princ.',
  'protocole': 'Proto.',
  'modèle': 'Mod.',
  'sécurité': 'Séc.'
};

export const BADGE_COLOR_MAP: { [key: string]: string } = {
    'activité': 'bg-emerald-100/75 text-emerald-800 border-emerald-200/90',
    'définition': 'bg-blue-100/75 text-blue-800 border-blue-200/90',
    'théorème': 'bg-purple-100/75 text-purple-800 border-purple-200/90',
    'proposition': 'bg-indigo-100/75 text-indigo-800 border-indigo-200/90',
    'lemme': 'bg-violet-100/75 text-violet-800 border-violet-200/90',
    'corollaire': 'bg-pink-100/75 text-pink-800 border-pink-200/90',
    'remarque': 'bg-slate-100/85 text-slate-700 border-slate-200/90',
    'preuve': 'bg-zinc-100 text-zinc-800 border-zinc-200/90',
    'exemple': 'bg-cyan-100/75 text-cyan-800 border-cyan-200/90',
    'exercice': 'bg-amber-100/80 text-amber-800 border-amber-200/90',
    'application': 'bg-teal-100/75 text-teal-800 border-teal-200/90',
    'introduction': 'bg-neutral-100/85 text-neutral-800 border-neutral-200/90',
    'observation': 'bg-sky-100/75 text-sky-800 border-sky-200/90',
    'comparaison': 'bg-lime-100/75 text-lime-800 border-lime-200/90',
    'classification': 'bg-orange-100/75 text-orange-800 border-orange-200/90',
    'structure': 'bg-rose-100/75 text-rose-800 border-rose-200/90',
    'fonction': 'bg-fuchsia-100/75 text-fuchsia-800 border-fuchsia-200/90',
    'mécanisme': 'bg-red-100/75 text-red-800 border-red-200/90',
    'processus': 'bg-green-100/75 text-green-800 border-green-200/90',
    'méthode': 'bg-stone-100/85 text-stone-700 border-stone-200/90',
    'expérience': 'bg-yellow-100/80 text-yellow-800 border-yellow-200/90',
    'interprétation': 'bg-cyan-100/75 text-cyan-800 border-cyan-200/90',
    'conclusion': 'bg-indigo-100/75 text-indigo-800 border-indigo-200/90',
    'propriété': 'bg-amber-100/80 text-amber-800 border-amber-200/90',
    'grandeur': 'bg-teal-100/75 text-teal-800 border-teal-200/90',
    'relation': 'bg-violet-100/75 text-violet-800 border-violet-200/90',
    'loi': 'bg-slate-100/85 text-slate-800 border-slate-200/90',
    'principe': 'bg-purple-100/75 text-purple-800 border-purple-200/90',
    'protocole': 'bg-emerald-100/75 text-emerald-800 border-emerald-200/90',
    'modèle': 'bg-blue-100/75 text-blue-800 border-blue-200/90',
    'sécurité': 'bg-red-100/75 text-red-800 border-red-200/90',
};

export const BADGE_TOOLTIP_MAP: { [key: string]: string } = {
  'activité': 'Activité',
  'définition': 'Définition',
  'théorème': 'Théorème',
  'proposition': 'Proposition',
  'lemme': 'Lemme',
  'corollaire': 'Corollaire',
  'remarque': 'Remarque',
  'preuve': 'Preuve',
  'exemple': 'Exemple',
  'exercice': 'Exercice',
  'application': "Exercice d'application",
  'introduction': 'Introduction',
  'observation': 'Observation',
  'comparaison': 'Comparaison',
  'classification': 'Classification',
  'structure': 'Structure',
  'fonction': 'Fonction',
  'mécanisme': 'Mécanisme',
  'processus': 'Processus',
  'méthode': 'Méthode',
  'expérience': 'Expérience',
  'interprétation': 'Interprétation',
  'conclusion': 'Conclusion',
  'propriété': 'Propriété',
  'grandeur': 'Grandeur',
  'relation': 'Relation',
  'loi': 'Loi',
  'principe': 'Principe',
  'protocole': 'Protocole',
  'modèle': 'Modèle',
  'sécurité': 'Sécurité',
};

export const SUBJECT_ABBREV_MAP: Record<string, string> = {
  'Mathématiques': 'Mathématiques',
  'Physique': 'Physique',
  'Économie': 'Économie',
  'Français': 'Français',
  'SVT': 'SVT',
  'Sciences de la Vie': 'SVT',
  'Sciences de la Vie et de la Terre': 'SVT',
};

/** Normalise un type importé (alias FR/EN, accents) vers la clé canonique. */
export const normalizeContentType = (type: string): string =>
  TYPE_MAP[(type || '').toLowerCase()] || type;
