import { GraduationCap, School, FlaskConical } from '@/components/ui/icons';
import { SUBJECTS, classLevelGroupsForCycle } from '@/constants';
import type { Cycle } from '@/types';
import type { ClassLevelGroup, CycleOption, ModalLang, OnboardingCopy } from './types';

export const ONBOARDING_CYCLES: CycleOption[] = [
    { key: 'college', icon: School },
    { key: 'lycee', icon: GraduationCap },
    { key: 'prepa', icon: FlaskConical },
];

export const LEVEL_GROUPS: Record<Cycle, ClassLevelGroup[]> = {
    college: classLevelGroupsForCycle('college'),
    lycee: classLevelGroupsForCycle('lycee'),
    prepa: classLevelGroupsForCycle('prepa'),
};

export const defaultLevelForCycle = (cycle: Cycle): string => LEVEL_GROUPS[cycle][0]?.levels[0] ?? '';

export const subjectOptionsFor = (selectedSubjects: string[] | undefined): string[] =>
    Array.from(new Set([...SUBJECTS, ...(selectedSubjects ?? [])]));

const TEXTS: Record<ModalLang, OnboardingCopy> = {
    fr: {
        brand: 'Mon cahier',
        title: 'Bienvenue',
        subtitle: 'Configurez votre espace de travail en quelques étapes.',
        start: 'Terminer la configuration',
        finishing: 'Finalisation…',
        configurationCompleted: 'Configuration enregistrée.',
        configurationError: 'La configuration n’a pas pu être finalisée. Réessayez.',
        classAdded: 'Classe ajoutée.',
        addingClass: 'Ajout…',
        classCreationError: 'Impossible d’ajouter la classe. Réessayez.',
        sectionLanguage: 'Langue',
        sectionProfile: 'Vos informations',
        sectionSubjects: 'Matières enseignées',
        sectionClasses: 'Mes classes',
        sectionSchedule: 'Emploi du temps',
        languageSelect: 'Choisissez votre langue principale',
        fullName: 'Nom complet',
        fullNamePlaceholder: 'Ex. : M. Ahmed Benali',
        establishment: 'Établissement',
        establishmentPlaceholder: 'Ex. : Lycée Ibn al-Haytham',
        teachingCycle: 'Cycle d’enseignement',
        cycleSelectionHint: 'Sélectionnez au moins un cycle pour continuer.',
        subjectSelectionHint: teacherName => `${teacherName}, choisissez vos matières d'enseignement pour pouvoir créer vos classes.`,
        subjectToAssign: 'Matière à affecter',
        assignSubjectHint: 'Sélectionnez la matière pour cette classe',
        otherSubject: 'Autre matière…',
        assignedSubject: 'Matière',
        levelPlaceholder: 'Niveau / filière',
        groupPlaceholder: 'N° 1–99',
        removeCreatedClass: 'Supprimer cette classe',
        classRemoved: name => `${name} a été supprimée.`,
        addClass: 'Ajouter cette classe',
        catalogMode: 'Niveau et groupe',
        manualMode: 'Nom personnalisé',
        customClassName: 'Nom de la classe',
        customClassNamePlaceholder: 'Ex. : Atelier de soutien — groupe A',
        customNameQuestion: 'Voulez-vous donner un nom personnalisé à cette classe ?',
        switchToCatalogQuestion: 'Revenir au choix du niveau et groupe',
        groupHint: 'Choisissez un niveau et un numéro, ou saisissez un nom personnalisé.',
        missingGroup: 'Indiquez le numéro de groupe.',
        invalidGroup: 'Utilisez un numéro de 1 à 99.',
        missingLabel: 'Saisissez le nom de la classe.',
        existingClass: 'Cette classe existe déjà.',
        understood: 'J’ai compris',
        finishWithoutSchedule: 'Terminer sans emploi du temps',
        back: 'Retour',
        next: 'Suivant',
        ignoreClass: 'Terminer sans classe',
        step: (current, total) => `Étape ${current} sur ${total}`,
        cycleLabels: { college: 'Collège', lycee: 'Lycée qualifiant', prepa: 'Prépa' },
        cycleDescriptions: { college: '1AC à 3AC', lycee: 'TC, 1BAC, 2BAC', prepa: 'CPGE (1ère & 2ème année)' },
        levelGroupLabels: { college: 'Collège', common: 'Tronc commun', firstBac: '1re Bac', secondBac: '2e Bac', prepa: 'Classes préparatoires', prepaFirst: '1re année CPGE', prepaSecond: '2e année CPGE' },
        selectBranchesHint: 'Cochez vos filières et cliquez sur vos groupes pour ajouter vos classes instantanément.',
        prepaPathHint: 'Parcours : MPSI → MP · PCSI → PSI · TSI, ECS et ECT sur deux années.',
        noClassSelectedYet: 'Aucune classe configurée pour le moment.',
        configuredClassesCount: count => `${count} classe${count > 1 ? 's' : ''} prête${count > 1 ? 's' : ''}`,
        customClassPrompt: '+ Ajouter une classe personnalisée (nom libre)',
        groupPrefix: 'Gr.',
        otherGroupNumber: 'Autre n°',
        groupsLabel: 'Groupes :',
    },
    ar: {
        brand: 'دفتر النصوص',
        title: 'مرحباً',
        subtitle: 'لنأخذ بضع لحظات لإعداد مساحة العمل الخاصة بك.',
        start: 'إنهاء الإعداد',
        finishing: 'جارٍ الإنهاء…',
        configurationCompleted: 'تم حفظ الإعدادات.',
        configurationError: 'تعذّر إنهاء الإعداد. حاول مرة أخرى.',
        classAdded: 'تمت إضافة القسم.',
        addingClass: 'جارٍ الإضافة…',
        classCreationError: 'تعذرت إضافة القسم. حاول مرة أخرى.',
        sectionLanguage: 'اللغة',
        sectionProfile: 'الملف الشخصي',
        sectionSubjects: 'المواد الدراسية',
        sectionClasses: 'أقسامك',
        sectionSchedule: 'استعمال الزمن',
        languageSelect: 'اختر لغتك الرئيسية',
        fullName: 'الاسم الكامل',
        fullNamePlaceholder: 'مثال: الأستاذ أحمد بنعلي',
        establishment: 'المؤسسة',
        establishmentPlaceholder: 'مثال: ثانوية ابن الهيثم',
        teachingCycle: 'السلك التعليمي',
        cycleSelectionHint: 'اختر سلكاً تعليمياً واحداً على الأقل للمتابعة.',
        subjectSelectionHint: teacherName => `الأستاذ ${teacherName}، اختر المواد التي تدرّسها لإنشاء أقسامك.`,
        subjectToAssign: 'المادة المسندة للقسم',
        assignSubjectHint: 'حدد المادة المسندة لهذا القسم',
        otherSubject: 'مادة أخرى…',
        assignedSubject: 'المادة',
        levelPlaceholder: 'المستوى / الشعبة',
        groupPlaceholder: 'رقم المجموعة (1–99)',
        removeCreatedClass: 'حذف هذا القسم',
        classRemoved: name => `تم حذف ${name}.`,
        addClass: 'إضافة هذا القسم',
        catalogMode: 'المستوى والمجموعة',
        manualMode: 'اسم مخصص',
        customClassName: 'اسم القسم',
        customClassNamePlaceholder: 'مثال: حصة الدعم — المجموعة أ',
        customNameQuestion: 'هل تريد إضافة تسمية خاصة لهذا القسم؟',
        switchToCatalogQuestion: 'العودة إلى اختيار المستوى والمجموعة',
        groupHint: 'اختر المستوى وأدخل رقم المجموعة، أو اكتب تسمية خاصة.',
        missingGroup: 'أدخل رقم المجموعة.',
        invalidGroup: 'استخدم رقماً من 1 إلى 99.',
        missingLabel: 'أدخل اسم القسم.',
        existingClass: 'هذا القسم موجود بالفعل.',
        understood: 'فهمت',
        finishWithoutSchedule: 'إنهاء بدون استعمال الزمن',
        back: 'رجوع',
        next: 'التالي',
        ignoreClass: 'إنهاء بدون إضافة قسم',
        step: (current, total) => `المرحلة ${current} من ${total}`,
        cycleLabels: { college: 'الثانوي الإعدادي', lycee: 'الثانوي التأهيلي', prepa: 'الأقسام التحضيرية للمدارس العليا' },
        cycleDescriptions: { college: 'من الأولى إلى الثالثة من التعليم الثانوي الإعدادي', lycee: 'الجذع المشترك وسلك البكالوريا', prepa: 'السنة الأولى والثانية' },
        levelGroupLabels: { college: 'الثانوي الإعدادي', common: 'الجذع المشترك', firstBac: 'الأولى بكالوريا', secondBac: 'الثانية بكالوريا', prepa: 'الأقسام التحضيرية', prepaFirst: 'السنة الأولى CPGE', prepaSecond: 'السنة الثانية CPGE' },
        selectBranchesHint: 'حدد الشعب المسندة إليك وانقر على أرقام المجموعات لإضافتها فوراً.',
        prepaPathHint: 'المسارات: MPSI / MP · PCSI / PSI · وTSI وECS وECT خلال سنتين.',
        noClassSelectedYet: 'لم يتم تحديد أي قسم بعد.',
        configuredClassesCount: count => count === 1 ? 'قسم واحد جاهز' : count === 2 ? 'قسمان جاهزان' : `${count} أقسام جاهزة`,
        customClassPrompt: '+ إضافة قسم بتسمية خاصة',
        groupPrefix: 'فوج',
        otherGroupNumber: 'رقم آخر',
        groupsLabel: 'المجموعات:',
    },
};

export const copyFor = (lang: ModalLang): OnboardingCopy => TEXTS[lang];
